# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install SDK'
  inputs:
    version: '3.0.100-preview6-012264'
- script: dotnet build Toss.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build Toss.sln'
- script: dotnet test ./Toss.Tests/Toss.Tests.csproj  --configuration $(buildConfiguration) --no-build  -v q --logger trx;LogFileName=test.trx
  displayName: 'Tests'
- script: dotnet test ./Toss.Tests.E2E/Toss.Tests.E2E.csproj  --configuration $(buildConfiguration)  --no-build  -v q --logger trx;LogFileName=e2e.trx
  displayName: 'E2E Tests'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues', 'Failed')
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
