version: '3.5'
secrets:
  tossserver2:
    # secret location on mac
    # file: ~/.microsoft/usersecrets/<userSecretsId>/secrets.json
    # secret location on windows
    file: $APPDATA\Microsoft\UserSecrets\ae68635e-649c-4f23-a39b-24a5ea3987f4\secrets.json
  raven_license:
    file: ./Hosting/RavenDB/license.json
services:    
  web:
    image: localhost:5000/toss
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RavenDBEndpoint: "http://ravendb:8080"
    ports:
      - 80:80
    secrets:
      - source: tossserver2
        target: tossserver
  ravendb:
    image: ravendb/ravendb
    volumes: 
      - ./Hosting/RavenDB:/root/ravendb
    environment:
      RAVEN_ARGS: "--Setup.Mode=None -c /root/ravendb/settings.json"     
    ports:
      - 8080:8080
    secrets:
      - raven_license